[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run railway:start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environment]
NODE_ENV = "production"