[providers]
nodejs = "18"

[build]
nixpkgs = ["nodejs-18_x", "npm-9_x"]

[phases.setup]
nixpkgs = ["nodejs-18_x", "npm-9_x"]

[phases.install]
cmd = "npm install"

[phases.build]
cmd = "npm run railway:build"

[phases.start]
cmd = "npm run railway:start"

[variables]
NODE_ENV = "production"
NIXPACKS_BUILD_CMD = "npm run railway:build"
NIXPACKS_START_CMD = "node serve.js"
DISABLE_NEXT_TELEMETRY = "1"

[options]
disable_auto_detection = true